const Data = [
  {
    id: "1",
    title: "弔事の連絡（代理）",
    status: "in-progress",
    column: "1",
    info: [
      { label: "申請日", value: "2021/01/29", modifiers: "long" },
      {
        label: "従業員名",
        value: "山田 太郎（あなた",
        modifiers: "long",
      },
      { label: "従業員名", value: "山田 太郎（あなた", modifiers: "long" },
      { label: "代理申請者", value: "-", modifiers: "long" },
    ],
  },
  {
    id: "2",
    title: "弔事の連絡（代理）",
    status: "in-progress",
    info: [
      { label: "申請日", value: "2021/01/29", modifiers: "long" },
      {
        label: "従業員名",
        value: "山田 太郎（あなた",
        modifiers: "long",
      },
      { label: "従業員名", value: "山田 太郎（あなた", modifiers: "long" },
      { label: "代理申請者", value: "-", modifiers: "long" },
    ],
  },
  {
    id: "3",
    title: "弔事の連絡（代理）",
    status: "in-progress",
    info: [
      { label: "申請日", value: "2021/01/29", modifiers: "long" },
      {
        label: "従業員名",
        value: "山田 太郎（あなた",
        modifiers: "long",
      },
      { label: "従業員名", value: "山田 太郎（あなた", modifiers: "long" },
      { label: "代理申請者", value: "-", modifiers: "long" },
    ],
  },
  {
    id: "4",
    title: "弔事の連絡（代理）",
    status: "in-progress",
    info: [
      { label: "申請日", value: "2021/01/29", modifiers: "long" },
      {
        label: "従業員名従",
        value: "山田 太郎（あなた",
        modifiers: "long",
      },
      { label: "従業員名", value: "山田 太郎（あなた", modifiers: "long" },
      { label: "従業員名", value: "山田 太郎（あなた", modifiers: "long" },
      { label: "従業員名", value: "山田 太郎（あなた", modifiers: "long" },
      { label: "従業員名", value: "山田 太郎（あなた", modifiers: "long" },
      { label: "従業員名", value: "山田 太郎（あなた", modifiers: "long" },
      { label: "従業員名", value: "山田 太郎（あなた", modifiers: "long" },
      { label: "従業員名", value: "山田 太郎（あなた", modifiers: "long" },
      { label: "従業員名", value: "山田 太郎（あなた", modifiers: "long" },
      { label: "従業員名", value: "山田 太郎（あなた", modifiers: "long" },
      { label: "従業員名", value: "山田 太郎（あなた", modifiers: "long" },
      { label: "従業員名", value: "山田 太郎（あなた", modifiers: "long" },
      { label: "代理申請者", value: "-", modifiers: "long" },
    ],
  },
  {
    id: "5",
    title: "弔事の連絡（代理）",
    status: "in-progress",
    info: [
      { label: "申請日", value: "2021/01/29", modifiers: "long" },
      {
        label: "従業員名従",
        value: "山田 太郎（あなた",
        modifiers: "long",
      },
      { label: "従業員名", value: "山田 太郎（あなた", modifiers: "long" },
      { label: "従業員名", value: "山田 太郎（あなた", modifiers: "long" },
      { label: "従業員名", value: "山田 太郎（あなた", modifiers: "long" },
      { label: "従業員名", value: "山田 太郎（あなた", modifiers: "long" },
      { label: "従業員名", value: "山田 太郎（あなた", modifiers: "long" },
      { label: "従業員名", value: "山田 太郎（あなた", modifiers: "long" },
      { label: "従業員名", value: "山田 太郎（あなた", modifiers: "long" },
      { label: "従業員名", value: "山田 太郎（あなた", modifiers: "long" },
      { label: "従業員名", value: "山田 太郎（あなた", modifiers: "long" },
      { label: "従業員名", value: "山田 太郎（あなた", modifiers: "long" },
      { label: "従業員名", value: "山田 太郎（あなた", modifiers: "long" },
      { label: "代理申請者", value: "-", modifiers: "long" },
    ],
  },
  {
    id: "6",
    title: "弔事の連絡（代理）",
    status: "approval",
    info: [
      { label: "申請日", value: "2021/01/29", modifiers: "long" },
      { label: "従業員名", value: "山田 太郎（あなた", modifiers: "long" },
      { label: "従業員名", value: "山田 太郎（あなた", modifiers: "long" },
      { label: "従業員名", value: "山田 太郎（あなた", modifiers: "long" },
      { label: "従業員名", value: "山田 太郎（あなた", modifiers: "long" },
      { label: "従業員名", value: "山田 太郎（あなた", modifiers: "long" },
      { label: "従業員名", value: "山田 太郎（あなた", modifiers: "long" },
      { label: "従業員名", value: "山田 太郎（あなた", modifiers: "long" },
      { label: "従業員名", value: "山田 太郎（あなた", modifiers: "long" },
      { label: "従業員名", value: "山田 太郎（あなた", modifiers: "long" },
      { label: "従業員名", value: "山田 太郎（あなた", modifiers: "long" },
      { label: "従業員名", value: "山田 太郎（あなた", modifiers: "long" },
      { label: "従業員名", value: "山田 太郎（あなた", modifiers: "long" },
      { label: "代理申請者", value: "-", modifiers: "long" },
    ],
  },
  {
    id: "7",
    title: "弔事の連絡（代理）",
    status: "remand",
    info: [
      { label: "申請日", value: "2021/01/29", modifiers: "long" },
      { label: "従業員名", value: "山田 太郎（あなた", modifiers: "long" },
      { label: "代理申請者", value: "-", modifiers: "long" },
    ],
  },
  {
    id: "8",
    title: "弔事の連絡（代理）",
    status: "remand",
    info: [
      { label: "申請日", value: "2021/01/29", modifiers: "long" },
      { label: "従業員名", value: "山田 太郎（あなた", modifiers: "long" },
      { label: "従業員名", value: "山田 太郎（あなた", modifiers: "long" },
      { label: "従業員名", value: "山田 太郎（あなた", modifiers: "long" },
    ],
  },
  {
    id: "9",
    title: "弔事の連絡（代理）",
    status: "remand",
    info: [
      { label: "申請日", value: "2021/01/29", modifiers: "long" },
      { label: "従業員名", value: "山田 太郎（あなた", modifiers: "long" },
      { label: "従業員名", value: "山田 太郎（あなた", modifiers: "long" },
      { label: "従業員名", value: "山田 太郎（あなた", modifiers: "long" },
    ],
  },
  {
    id: "10",
    title: "弔事の連絡（代理）",
    status: "remand",
    info: [
      { label: "申請日", value: "2021/01/29", modifiers: "long" },
      { label: "従業員名", value: "山田 太郎（あなた", modifiers: "long" },
      { label: "従業員名", value: "山田 太郎（あなた", modifiers: "long" },
      { label: "従業員名", value: "山田 太郎（あなた", modifiers: "long" },
    ],
  },
  {
    id: "11",
    title: "弔事の連絡（代理）",
    status: "remand",
    info: [
      { label: "申請日", value: "2021/01/29", modifiers: "long" },
      { label: "従業員名", value: "山田 太郎（あなた", modifiers: "long" },
      { label: "従業員名", value: "山田 太郎（あなた", modifiers: "long" },
      { label: "従業員名", value: "山田 太郎（あなた", modifiers: "long" },
    ],
  },
  {
    id: "12",
    title: "弔事の連絡（代理）",
    status: "remand",
    info: [
      { label: "申請日", value: "2021/01/29", modifiers: "long" },
      { label: "従業員名", value: "山田 太郎（あなた", modifiers: "long" },
      { label: "従業員名", value: "山田 太郎（あなた", modifiers: "long" },
      { label: "従業員名", value: "山田 太郎（あなた", modifiers: "long" },
    ],
  },
  {
    id: "13",
    title: "弔事の連絡（代理）",
    status: "remand",
    info: [
      { label: "申請日", value: "2021/01/29", modifiers: "long" },
      { label: "従業員名", value: "山田 太郎（あなた", modifiers: "long" },
      { label: "従業員名", value: "山田 太郎（あなた", modifiers: "long" },
      { label: "従業員名", value: "山田 太郎（あなた", modifiers: "long" },
    ],
  },
];

export default Data;
